In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [9]:
a = [1,2,3,4]

In [10]:
c = np.copy(a)       #deep copy

In [11]:
c

array([1, 2, 3, 4])

In [12]:
a[1]=100

In [13]:
c

array([1, 2, 3, 4])

In [14]:
a

[1, 100, 3, 4]

In [15]:
c[0] = 200

In [16]:
c

array([200,   2,   3,   4])

In [17]:
a

[1, 100, 3, 4]

In [18]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [20]:
np.fromfunction(lambda i,j : i+j ,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [21]:
w = np.fromfunction(lambda i,j : i-j ,(3,3))

In [22]:
w

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [23]:
w.ndim

2

In [24]:
iterable = (i*i for i in range(5))

In [25]:
np.fromiter(iterable , int)

array([ 0,  1,  4,  9, 16])

In [26]:
np.fromstring('4 5' ,sep='  '  )

array([4., 5.])

In [27]:
 np.fromstring('4,5,6,7' , sep=','  )

array([4., 5., 6., 7.])

In [28]:
l 

[1, 2, 3, 4, 5]

In [29]:
ar = np.array(l)

In [30]:
ar.ndim

1

In [31]:
a= [[[1,2,3,4],[0,1,2,3]]]
a

[[[1, 2, 3, 4], [0, 1, 2, 3]]]

In [32]:
ar3 =np.array(a)
ar3

array([[[1, 2, 3, 4],
        [0, 1, 2, 3]]])

In [33]:
ar3.ndim

3

In [34]:
ar3.shap

AttributeError: 'numpy.ndarray' object has no attribute 'shap'

In [35]:
ar

array([1, 2, 3, 4, 5])

In [36]:
ar.shape

(5,)

In [37]:
ar3.dtype

dtype('int64')

In [38]:
ar.dtype

dtype('int64')

In [39]:
np.arange(0.1,6.1)

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1])

In [40]:
list(np.arange(1.2,6.5,.5))

[1.2, 1.7, 2.2, 2.7, 3.2, 3.7, 4.2, 4.7, 5.2, 5.7, 6.2]

In [41]:
np.linspace(1,6,12)

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
ar = np.zeros((3,4,3,2))

In [45]:
ar.ndim

4

In [46]:
ar

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [47]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
a=np.ones((2,4,3))

In [49]:
c = a *2

In [50]:
c

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

In [51]:
c+5

array([[[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]]])

In [52]:
np.empty((5,4))

array([[4.65393689e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000,             nan,
        0.00000000e+000]])

In [53]:
a =np.eye((4)) 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
import pandas as pd

In [55]:
pd.DataFrame(a)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [56]:
np.logspace(2,5 ,7)     # finding logarith  "2,3,4,5"

array([   100.        ,    316.22776602,   1000.        ,   3162.27766017,
        10000.        ,  31622.77660168, 100000.        ])

In [57]:
np.random.randn(3,4)

array([[ 0.27193313,  0.2355994 , -0.43413044,  0.23149434],
       [-0.31245607,  0.8209889 ,  0.64257773,  0.81899938],
       [ 0.11890656,  1.46887301, -0.53414511, -1.14172474]])

In [58]:
ar = np.random.rand(3,4)
ar

array([[0.10288044, 0.30861487, 0.50312724, 0.91245998],
       [0.28390352, 0.99450079, 0.49203798, 0.54949464],
       [0.80049233, 0.92283436, 0.65794235, 0.10870355]])

In [59]:
import pandas as pd

In [60]:
pd.DataFrame(ar)

0         1         2         3
0  0.102880  0.308615  0.503127  0.912460
1  0.283904  0.994501  0.492038  0.549495
2  0.800492  0.922834  0.657942  0.108704

In [61]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
pd.DataFrame(a)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [63]:
ar = np.random.rand(3,4)

In [64]:
np.random.randint(3,4 ,(50,60))

array([[3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])

In [65]:
pd.DataFrame(np.random.randint(3,4 ,(50,60))).to_csv("text.csv")

In [66]:
ar = np.random.rand(3,4)
ar

array([[0.19038729, 0.98395413, 0.18357189, 0.84235619],
       [0.55576409, 0.22972003, 0.88063783, 0.75915116],
       [0.2042978 , 0.25644789, 0.91323835, 0.13398439]])

In [67]:
s = ar.reshape(6,2)
s

array([[0.19038729, 0.98395413],
       [0.18357189, 0.84235619],
       [0.55576409, 0.22972003],
       [0.88063783, 0.75915116],
       [0.2042978 , 0.25644789],
       [0.91323835, 0.13398439]])

In [68]:
s[0][0]

0.19038728684585804

In [69]:
s[1:4:,0]

array([0.18357189, 0.55576409, 0.88063783])

In [70]:
ar = np.random.randint(3,40 ,(4,5))
ar

array([[38, 31, 11, 27, 21],
       [20, 35, 25, 16, 23],
       [28,  4, 22, 14, 29],
       [12, 10, 12, 26, 10]])

In [71]:
ar>20   # to collect data is grater than 20

array([[ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True, False,  True],
       [False, False, False,  True, False]])

In [72]:
ar[ar>20]   #to collect data is grater than 20

array([38, 31, 27, 21, 35, 25, 23, 28, 22, 29, 26])

In [73]:
ar[1:3,[2,3]]

array([[25, 16],
       [22, 14]])

In [74]:
ar[2:4,[3,4]]

array([[14, 29],
       [26, 10]])

In [75]:
ar[0][0]=100
ar

array([[100,  31,  11,  27,  21],
       [ 20,  35,  25,  16,  23],
       [ 28,   4,  22,  14,  29],
       [ 12,  10,  12,  26,  10]])

In [76]:
ar[3][4] =1000
ar

array([[ 100,   31,   11,   27,   21],
       [  20,   35,   25,   16,   23],
       [  28,    4,   22,   14,   29],
       [  12,   10,   12,   26, 1000]])

In [77]:
ar1 = np.random.randint(1,3 ,(3,3))
ar2= np.random.randint(1,3 ,(3,3))

In [78]:
ar1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [79]:
ar2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [80]:
ar1+ar2

array([[4, 4, 3],
       [3, 4, 3],
       [2, 3, 3]])

In [81]:
ar1*ar2

array([[4, 4, 2],
       [2, 4, 2],
       [1, 2, 2]])

In [82]:
ar1@ar2    #Proper mattrix multiplication

array([[ 9, 10,  7],
       [ 8, 10,  6],
       [ 6,  8,  5]])

In [83]:
ar1+1

array([[3, 3, 2],
       [2, 3, 3],
       [2, 2, 3]])

In [84]:
ar2 *2

array([[4, 4, 4],
       [4, 4, 2],
       [2, 4, 2]])

In [85]:
ar =np.zeros((4,4))

In [86]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
row = np.array([1,2,3,4])

In [88]:
ar+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [89]:
col = np.array([[1,2,3,4]])

In [90]:
ar+col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [91]:
ar*col.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Numpy part two

In [92]:
# Numpy 

In [93]:
arr = [1,2,3,4]

In [94]:
arr

[1, 2, 3, 4]

In [95]:
np.array(arr)

array([1, 2, 3, 4])

In [96]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [97]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [98]:
np.power(arr,2)

array([ 1,  4,  9, 16])

In [106]:
arr = np.array([1,2,0,0,0,0,3,4,5,5,666])

In [107]:
arr

array([  1,   2,   0,   0,   0,   0,   3,   4,   5,   5, 666])

In [108]:
np.short(arr)

array([  1,   2,   0,   0,   0,   0,   3,   4,   5,   5, 666], dtype=int16)

In [109]:
np.searchsorted(arr ,22)

10

In [110]:
arr

array([  1,   2,   0,   0,   0,   0,   3,   4,   5,   5, 666])

In [112]:
np.count_nonzero(arr)

7

In [113]:
np.where(arr > 4)

(array([ 8,  9, 10]),)

In [116]:
np.extract(arr>3 ,arr)

array([  4,   5,   5, 666])

In [117]:
# copy & swap

In [118]:
arr

array([  1,   2,   0,   0,   0,   0,   3,   4,   5,   5, 666])

In [121]:
a = np.copy(arr)    ## deep copy

In [122]:
a

array([  1,   2,   0,   0,   0,   0,   3,   4,   5,   5, 666])

In [123]:
b = arr   # solo coy


In [124]:
b

array([  1,   2,   0,   0,   0,   0,   3,   4,   5,   5, 666])

In [125]:
arr[1] = 0

In [126]:
arr

array([  1,   0,   0,   0,   0,   0,   3,   4,   5,   5, 666])

In [127]:
b

array([  1,   0,   0,   0,   0,   0,   3,   4,   5,   5, 666])

In [128]:
a

array([  1,   2,   0,   0,   0,   0,   3,   4,   5,   5, 666])

In [129]:
# numpy - matrix library

In [130]:
import numpy.matlib as nm

In [131]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [133]:
nm.zeros((5,5))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [136]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [137]:
# linear algebra

In [143]:
arr1 = np.random.randint(3,4,(4,4))
arr2 = np.random.randint(2,3 , (4,4))

In [144]:
arr1

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [145]:
arr2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [146]:
np.dot(arr1,arr2 )   # for DOT product

array([[24, 24, 24, 24],
       [24, 24, 24, 24],
       [24, 24, 24, 24],
       [24, 24, 24, 24]])

In [148]:
arr1@arr2   #also find dot product

array([[24, 24, 24, 24],
       [24, 24, 24, 24],
       [24, 24, 24, 24],
       [24, 24, 24, 24]])

In [7]:
arr1 = np.random.randint(1,2,(2,2))
arr2 = np.random.randint(1,2,(2,2))

In [9]:
arr1

array([[1, 1],
       [1, 1]])

In [10]:
arr2

array([[1, 1],
       [1, 1]])

In [11]:
arr1@arr2

array([[2, 2],
       [2, 2]])